# Generated by Django 4.2 on 2023-04-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='picture',
        ),
    ]
