# Generated by Django 4.2 on 2023-05-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_forecaster_report_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='forecaster',
        ),
    ]
