# Generated by Django 4.2.1 on 2023-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('page_count', models.IntegerField(default=0)),
                ('categories', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
