# Generated by Django 4.2.1 on 2023-05-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_book_rating_book_number_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book_app.bookreview'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
