# Generated by Django 4.2 on 2023-05-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_category_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
